# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.FileField(help_text='Please upload file of size.', max_length=200, upload_to='slideshow', validators=[website.models.file_extension])),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
