# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('sidebar_description', models.TextField()),
                ('image', models.FileField(help_text='Image should be in jpg, png or jpeg format and size be 2000px * 1000px', max_length=200, upload_to='aboutus', validators=[website.models.file_extension])),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=5)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=models.FileField(help_text='Image should be in jpg, png or jpeg format and size be 2000px * 1000px', max_length=200, upload_to='slideshow', validators=[website.models.file_extension]),
        ),
    ]
