# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160925_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(help_text='Image should be in jpg, png or jpeg format.', max_length=200, upload_to='ourwork', validators=[website.models.file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='WhatIsVastu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.TextField()),
                ('answer2', models.TextField()),
                ('answer3', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact Info',
            },
        ),
    ]
