# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_project_whatisvastu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatisvastu',
            options={'verbose_name_plural': 'WhatIsVastu'},
        ),
    ]
