# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Query',
        ),
        migrations.AlterModelOptions(
            name='query',
            options={'verbose_name_plural': 'Queries'},
        ),
    ]
